CREATE OR REPLACE PACKAGE PK_REASSIGN AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
PROCEDURE REASSIGN_EMP(emp_id IN EMP.EMPNO%TYPE, new_DEPT_id IN DEPT.DEPTNO%TYPE,new_DEPT_name out DEPT.DNAME%TYPE);
END PK_REASSIGN;
/


CREATE OR REPLACE PACKAGE BODY PK_REASSIGN AS

  PROCEDURE REASSIGN_EMP(emp_id IN EMP.EMPNO%TYPE, new_DEPT_id IN DEPT.DEPTNO%TYPE,new_DEPT_name out DEPT.DNAME%TYPE) AS
      
  BEGIN
    Update EMP
    SET DEPTNO = new_DEPT_id
    WHERE EMPNO = emp_id;
   SELECT  DEPT.DNAME  into new_DEPT_name  FROM DEPT WHERE DEPT.DEPTNO=new_DEPT_id;
     END REASSIGN_EMP;

END PK_REASSIGN;
/
