package demo.model.dao;

import demo.model.dao.Customers;
import demo.model.dao.CustomersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    long countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByPrimaryKey(Short CUSTOMER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    Customers selectByPrimaryKey(Short CUSTOMER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExampleSelective(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExample(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKey(Customers record);
}