package demo.model.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CustomersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public CustomersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCUSTOMER_IDIsNull() {
            addCriterion("CUSTOMER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDIsNotNull() {
            addCriterion("CUSTOMER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDEqualTo(Short value) {
            addCriterion("CUSTOMER_ID =", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDNotEqualTo(Short value) {
            addCriterion("CUSTOMER_ID <>", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDGreaterThan(Short value) {
            addCriterion("CUSTOMER_ID >", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDGreaterThanOrEqualTo(Short value) {
            addCriterion("CUSTOMER_ID >=", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDLessThan(Short value) {
            addCriterion("CUSTOMER_ID <", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDLessThanOrEqualTo(Short value) {
            addCriterion("CUSTOMER_ID <=", value, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDIn(List<Short> values) {
            addCriterion("CUSTOMER_ID in", values, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDNotIn(List<Short> values) {
            addCriterion("CUSTOMER_ID not in", values, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDBetween(Short value1, Short value2) {
            addCriterion("CUSTOMER_ID between", value1, value2, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUSTOMER_IDNotBetween(Short value1, Short value2) {
            addCriterion("CUSTOMER_ID not between", value1, value2, "CUSTOMER_ID");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEIsNull() {
            addCriterion("CUST_FIRST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEIsNotNull() {
            addCriterion("CUST_FIRST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEEqualTo(String value) {
            addCriterion("CUST_FIRST_NAME =", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMENotEqualTo(String value) {
            addCriterion("CUST_FIRST_NAME <>", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEGreaterThan(String value) {
            addCriterion("CUST_FIRST_NAME >", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_FIRST_NAME >=", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMELessThan(String value) {
            addCriterion("CUST_FIRST_NAME <", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMELessThanOrEqualTo(String value) {
            addCriterion("CUST_FIRST_NAME <=", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMELike(String value) {
            addCriterion("CUST_FIRST_NAME like", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMENotLike(String value) {
            addCriterion("CUST_FIRST_NAME not like", value, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEIn(List<String> values) {
            addCriterion("CUST_FIRST_NAME in", values, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMENotIn(List<String> values) {
            addCriterion("CUST_FIRST_NAME not in", values, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMEBetween(String value1, String value2) {
            addCriterion("CUST_FIRST_NAME between", value1, value2, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_FIRST_NAMENotBetween(String value1, String value2) {
            addCriterion("CUST_FIRST_NAME not between", value1, value2, "CUST_FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEIsNull() {
            addCriterion("CUST_LAST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEIsNotNull() {
            addCriterion("CUST_LAST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEEqualTo(String value) {
            addCriterion("CUST_LAST_NAME =", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMENotEqualTo(String value) {
            addCriterion("CUST_LAST_NAME <>", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEGreaterThan(String value) {
            addCriterion("CUST_LAST_NAME >", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_LAST_NAME >=", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMELessThan(String value) {
            addCriterion("CUST_LAST_NAME <", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMELessThanOrEqualTo(String value) {
            addCriterion("CUST_LAST_NAME <=", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMELike(String value) {
            addCriterion("CUST_LAST_NAME like", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMENotLike(String value) {
            addCriterion("CUST_LAST_NAME not like", value, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEIn(List<String> values) {
            addCriterion("CUST_LAST_NAME in", values, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMENotIn(List<String> values) {
            addCriterion("CUST_LAST_NAME not in", values, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMEBetween(String value1, String value2) {
            addCriterion("CUST_LAST_NAME between", value1, value2, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_LAST_NAMENotBetween(String value1, String value2) {
            addCriterion("CUST_LAST_NAME not between", value1, value2, "CUST_LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1IsNull() {
            addCriterion("CUST_STREET_ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1IsNotNull() {
            addCriterion("CUST_STREET_ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1EqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS1 =", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1NotEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS1 <>", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1GreaterThan(String value) {
            addCriterion("CUST_STREET_ADDRESS1 >", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1GreaterThanOrEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS1 >=", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1LessThan(String value) {
            addCriterion("CUST_STREET_ADDRESS1 <", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1LessThanOrEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS1 <=", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1Like(String value) {
            addCriterion("CUST_STREET_ADDRESS1 like", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1NotLike(String value) {
            addCriterion("CUST_STREET_ADDRESS1 not like", value, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1In(List<String> values) {
            addCriterion("CUST_STREET_ADDRESS1 in", values, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1NotIn(List<String> values) {
            addCriterion("CUST_STREET_ADDRESS1 not in", values, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1Between(String value1, String value2) {
            addCriterion("CUST_STREET_ADDRESS1 between", value1, value2, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS1NotBetween(String value1, String value2) {
            addCriterion("CUST_STREET_ADDRESS1 not between", value1, value2, "CUST_STREET_ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2IsNull() {
            addCriterion("CUST_STREET_ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2IsNotNull() {
            addCriterion("CUST_STREET_ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2EqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS2 =", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2NotEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS2 <>", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2GreaterThan(String value) {
            addCriterion("CUST_STREET_ADDRESS2 >", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2GreaterThanOrEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS2 >=", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2LessThan(String value) {
            addCriterion("CUST_STREET_ADDRESS2 <", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2LessThanOrEqualTo(String value) {
            addCriterion("CUST_STREET_ADDRESS2 <=", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2Like(String value) {
            addCriterion("CUST_STREET_ADDRESS2 like", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2NotLike(String value) {
            addCriterion("CUST_STREET_ADDRESS2 not like", value, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2In(List<String> values) {
            addCriterion("CUST_STREET_ADDRESS2 in", values, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2NotIn(List<String> values) {
            addCriterion("CUST_STREET_ADDRESS2 not in", values, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2Between(String value1, String value2) {
            addCriterion("CUST_STREET_ADDRESS2 between", value1, value2, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_STREET_ADDRESS2NotBetween(String value1, String value2) {
            addCriterion("CUST_STREET_ADDRESS2 not between", value1, value2, "CUST_STREET_ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYIsNull() {
            addCriterion("CUST_CITY is null");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYIsNotNull() {
            addCriterion("CUST_CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYEqualTo(String value) {
            addCriterion("CUST_CITY =", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYNotEqualTo(String value) {
            addCriterion("CUST_CITY <>", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYGreaterThan(String value) {
            addCriterion("CUST_CITY >", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_CITY >=", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYLessThan(String value) {
            addCriterion("CUST_CITY <", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYLessThanOrEqualTo(String value) {
            addCriterion("CUST_CITY <=", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYLike(String value) {
            addCriterion("CUST_CITY like", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYNotLike(String value) {
            addCriterion("CUST_CITY not like", value, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYIn(List<String> values) {
            addCriterion("CUST_CITY in", values, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYNotIn(List<String> values) {
            addCriterion("CUST_CITY not in", values, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYBetween(String value1, String value2) {
            addCriterion("CUST_CITY between", value1, value2, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_CITYNotBetween(String value1, String value2) {
            addCriterion("CUST_CITY not between", value1, value2, "CUST_CITY");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEIsNull() {
            addCriterion("CUST_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEIsNotNull() {
            addCriterion("CUST_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEEqualTo(String value) {
            addCriterion("CUST_STATE =", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATENotEqualTo(String value) {
            addCriterion("CUST_STATE <>", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEGreaterThan(String value) {
            addCriterion("CUST_STATE >", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_STATE >=", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATELessThan(String value) {
            addCriterion("CUST_STATE <", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATELessThanOrEqualTo(String value) {
            addCriterion("CUST_STATE <=", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATELike(String value) {
            addCriterion("CUST_STATE like", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATENotLike(String value) {
            addCriterion("CUST_STATE not like", value, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEIn(List<String> values) {
            addCriterion("CUST_STATE in", values, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATENotIn(List<String> values) {
            addCriterion("CUST_STATE not in", values, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATEBetween(String value1, String value2) {
            addCriterion("CUST_STATE between", value1, value2, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_STATENotBetween(String value1, String value2) {
            addCriterion("CUST_STATE not between", value1, value2, "CUST_STATE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEIsNull() {
            addCriterion("CUST_POSTAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEIsNotNull() {
            addCriterion("CUST_POSTAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEEqualTo(String value) {
            addCriterion("CUST_POSTAL_CODE =", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODENotEqualTo(String value) {
            addCriterion("CUST_POSTAL_CODE <>", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEGreaterThan(String value) {
            addCriterion("CUST_POSTAL_CODE >", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_POSTAL_CODE >=", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODELessThan(String value) {
            addCriterion("CUST_POSTAL_CODE <", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODELessThanOrEqualTo(String value) {
            addCriterion("CUST_POSTAL_CODE <=", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODELike(String value) {
            addCriterion("CUST_POSTAL_CODE like", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODENotLike(String value) {
            addCriterion("CUST_POSTAL_CODE not like", value, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEIn(List<String> values) {
            addCriterion("CUST_POSTAL_CODE in", values, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODENotIn(List<String> values) {
            addCriterion("CUST_POSTAL_CODE not in", values, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODEBetween(String value1, String value2) {
            addCriterion("CUST_POSTAL_CODE between", value1, value2, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andCUST_POSTAL_CODENotBetween(String value1, String value2) {
            addCriterion("CUST_POSTAL_CODE not between", value1, value2, "CUST_POSTAL_CODE");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1IsNull() {
            addCriterion("PHONE_NUMBER1 is null");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1IsNotNull() {
            addCriterion("PHONE_NUMBER1 is not null");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1EqualTo(String value) {
            addCriterion("PHONE_NUMBER1 =", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1NotEqualTo(String value) {
            addCriterion("PHONE_NUMBER1 <>", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1GreaterThan(String value) {
            addCriterion("PHONE_NUMBER1 >", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1GreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER1 >=", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1LessThan(String value) {
            addCriterion("PHONE_NUMBER1 <", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1LessThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER1 <=", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1Like(String value) {
            addCriterion("PHONE_NUMBER1 like", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1NotLike(String value) {
            addCriterion("PHONE_NUMBER1 not like", value, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1In(List<String> values) {
            addCriterion("PHONE_NUMBER1 in", values, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1NotIn(List<String> values) {
            addCriterion("PHONE_NUMBER1 not in", values, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1Between(String value1, String value2) {
            addCriterion("PHONE_NUMBER1 between", value1, value2, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER1NotBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER1 not between", value1, value2, "PHONE_NUMBER1");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2IsNull() {
            addCriterion("PHONE_NUMBER2 is null");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2IsNotNull() {
            addCriterion("PHONE_NUMBER2 is not null");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2EqualTo(String value) {
            addCriterion("PHONE_NUMBER2 =", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2NotEqualTo(String value) {
            addCriterion("PHONE_NUMBER2 <>", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2GreaterThan(String value) {
            addCriterion("PHONE_NUMBER2 >", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2GreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER2 >=", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2LessThan(String value) {
            addCriterion("PHONE_NUMBER2 <", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2LessThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER2 <=", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2Like(String value) {
            addCriterion("PHONE_NUMBER2 like", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2NotLike(String value) {
            addCriterion("PHONE_NUMBER2 not like", value, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2In(List<String> values) {
            addCriterion("PHONE_NUMBER2 in", values, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2NotIn(List<String> values) {
            addCriterion("PHONE_NUMBER2 not in", values, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2Between(String value1, String value2) {
            addCriterion("PHONE_NUMBER2 between", value1, value2, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andPHONE_NUMBER2NotBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER2 not between", value1, value2, "PHONE_NUMBER2");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITIsNull() {
            addCriterion("CREDIT_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITIsNotNull() {
            addCriterion("CREDIT_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITEqualTo(BigDecimal value) {
            addCriterion("CREDIT_LIMIT =", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITNotEqualTo(BigDecimal value) {
            addCriterion("CREDIT_LIMIT <>", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITGreaterThan(BigDecimal value) {
            addCriterion("CREDIT_LIMIT >", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREDIT_LIMIT >=", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITLessThan(BigDecimal value) {
            addCriterion("CREDIT_LIMIT <", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREDIT_LIMIT <=", value, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITIn(List<BigDecimal> values) {
            addCriterion("CREDIT_LIMIT in", values, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITNotIn(List<BigDecimal> values) {
            addCriterion("CREDIT_LIMIT not in", values, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREDIT_LIMIT between", value1, value2, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCREDIT_LIMITNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREDIT_LIMIT not between", value1, value2, "CREDIT_LIMIT");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILIsNull() {
            addCriterion("CUST_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILIsNotNull() {
            addCriterion("CUST_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILEqualTo(String value) {
            addCriterion("CUST_EMAIL =", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILNotEqualTo(String value) {
            addCriterion("CUST_EMAIL <>", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILGreaterThan(String value) {
            addCriterion("CUST_EMAIL >", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_EMAIL >=", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILLessThan(String value) {
            addCriterion("CUST_EMAIL <", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILLessThanOrEqualTo(String value) {
            addCriterion("CUST_EMAIL <=", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILLike(String value) {
            addCriterion("CUST_EMAIL like", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILNotLike(String value) {
            addCriterion("CUST_EMAIL not like", value, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILIn(List<String> values) {
            addCriterion("CUST_EMAIL in", values, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILNotIn(List<String> values) {
            addCriterion("CUST_EMAIL not in", values, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILBetween(String value1, String value2) {
            addCriterion("CUST_EMAIL between", value1, value2, "CUST_EMAIL");
            return (Criteria) this;
        }

        public Criteria andCUST_EMAILNotBetween(String value1, String value2) {
            addCriterion("CUST_EMAIL not between", value1, value2, "CUST_EMAIL");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 06 13:15:56 GMT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DBUSER.DEMO_CUSTOMERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}