package demo.model.dao;

import java.math.BigDecimal;
/** one of the daos*/
public class Customers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short CUSTOMER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_FIRST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_FIRST_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_LAST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_LAST_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_STREET_ADDRESS1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_STREET_ADDRESS2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_CITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_CITY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_STATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_POSTAL_CODE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_POSTAL_CODE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String PHONE_NUMBER1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String PHONE_NUMBER2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CREDIT_LIMIT
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private BigDecimal CREDIT_LIMIT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_CUSTOMERS.CUST_EMAIL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String CUST_EMAIL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUSTOMER_ID
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for DBUSER.DEMO_CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUSTOMER_ID(Short CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_FIRST_NAME
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_FIRST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_FIRST_NAME() {
        return CUST_FIRST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_FIRST_NAME
     *
     * @param CUST_FIRST_NAME the value for DBUSER.DEMO_CUSTOMERS.CUST_FIRST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_FIRST_NAME(String CUST_FIRST_NAME) {
        this.CUST_FIRST_NAME = CUST_FIRST_NAME == null ? null : CUST_FIRST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_LAST_NAME
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_LAST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_LAST_NAME() {
        return CUST_LAST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_LAST_NAME
     *
     * @param CUST_LAST_NAME the value for DBUSER.DEMO_CUSTOMERS.CUST_LAST_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_LAST_NAME(String CUST_LAST_NAME) {
        this.CUST_LAST_NAME = CUST_LAST_NAME == null ? null : CUST_LAST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS1
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_STREET_ADDRESS1() {
        return CUST_STREET_ADDRESS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS1
     *
     * @param CUST_STREET_ADDRESS1 the value for DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_STREET_ADDRESS1(String CUST_STREET_ADDRESS1) {
        this.CUST_STREET_ADDRESS1 = CUST_STREET_ADDRESS1 == null ? null : CUST_STREET_ADDRESS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS2
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_STREET_ADDRESS2() {
        return CUST_STREET_ADDRESS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS2
     *
     * @param CUST_STREET_ADDRESS2 the value for DBUSER.DEMO_CUSTOMERS.CUST_STREET_ADDRESS2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_STREET_ADDRESS2(String CUST_STREET_ADDRESS2) {
        this.CUST_STREET_ADDRESS2 = CUST_STREET_ADDRESS2 == null ? null : CUST_STREET_ADDRESS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_CITY
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_CITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_CITY() {
        return CUST_CITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_CITY
     *
     * @param CUST_CITY the value for DBUSER.DEMO_CUSTOMERS.CUST_CITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_CITY(String CUST_CITY) {
        this.CUST_CITY = CUST_CITY == null ? null : CUST_CITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STATE
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_STATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_STATE() {
        return CUST_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_STATE
     *
     * @param CUST_STATE the value for DBUSER.DEMO_CUSTOMERS.CUST_STATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_STATE(String CUST_STATE) {
        this.CUST_STATE = CUST_STATE == null ? null : CUST_STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_POSTAL_CODE
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_POSTAL_CODE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_POSTAL_CODE() {
        return CUST_POSTAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_POSTAL_CODE
     *
     * @param CUST_POSTAL_CODE the value for DBUSER.DEMO_CUSTOMERS.CUST_POSTAL_CODE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_POSTAL_CODE(String CUST_POSTAL_CODE) {
        this.CUST_POSTAL_CODE = CUST_POSTAL_CODE == null ? null : CUST_POSTAL_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER1
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getPHONE_NUMBER1() {
        return PHONE_NUMBER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER1
     *
     * @param PHONE_NUMBER1 the value for DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER1
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setPHONE_NUMBER1(String PHONE_NUMBER1) {
        this.PHONE_NUMBER1 = PHONE_NUMBER1 == null ? null : PHONE_NUMBER1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER2
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getPHONE_NUMBER2() {
        return PHONE_NUMBER2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER2
     *
     * @param PHONE_NUMBER2 the value for DBUSER.DEMO_CUSTOMERS.PHONE_NUMBER2
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setPHONE_NUMBER2(String PHONE_NUMBER2) {
        this.PHONE_NUMBER2 = PHONE_NUMBER2 == null ? null : PHONE_NUMBER2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CREDIT_LIMIT
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CREDIT_LIMIT
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public BigDecimal getCREDIT_LIMIT() {
        return CREDIT_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CREDIT_LIMIT
     *
     * @param CREDIT_LIMIT the value for DBUSER.DEMO_CUSTOMERS.CREDIT_LIMIT
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCREDIT_LIMIT(BigDecimal CREDIT_LIMIT) {
        this.CREDIT_LIMIT = CREDIT_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_EMAIL
     *
     * @return the value of DBUSER.DEMO_CUSTOMERS.CUST_EMAIL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getCUST_EMAIL() {
        return CUST_EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_CUSTOMERS.CUST_EMAIL
     *
     * @param CUST_EMAIL the value for DBUSER.DEMO_CUSTOMERS.CUST_EMAIL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCUST_EMAIL(String CUST_EMAIL) {
        this.CUST_EMAIL = CUST_EMAIL == null ? null : CUST_EMAIL.trim();
    }
}