package demo.model.dao;

import java.math.BigDecimal;
import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.EMPNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short EMPNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.ENAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String ENAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.JOB
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String JOB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.MGR
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short MGR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.HIREDATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Date HIREDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.SAL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private BigDecimal SAL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.COMM
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private BigDecimal COMM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.EMP.DEPTNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short DEPTNO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.EMPNO
     *
     * @return the value of DBUSER.EMP.EMPNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getEMPNO() {
        return EMPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.EMPNO
     *
     * @param EMPNO the value for DBUSER.EMP.EMPNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setEMPNO(Short EMPNO) {
        this.EMPNO = EMPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.ENAME
     *
     * @return the value of DBUSER.EMP.ENAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getENAME() {
        return ENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.ENAME
     *
     * @param ENAME the value for DBUSER.EMP.ENAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setENAME(String ENAME) {
        this.ENAME = ENAME == null ? null : ENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.JOB
     *
     * @return the value of DBUSER.EMP.JOB
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getJOB() {
        return JOB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.JOB
     *
     * @param JOB the value for DBUSER.EMP.JOB
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setJOB(String JOB) {
        this.JOB = JOB == null ? null : JOB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.MGR
     *
     * @return the value of DBUSER.EMP.MGR
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getMGR() {
        return MGR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.MGR
     *
     * @param MGR the value for DBUSER.EMP.MGR
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setMGR(Short MGR) {
        this.MGR = MGR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.HIREDATE
     *
     * @return the value of DBUSER.EMP.HIREDATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Date getHIREDATE() {
        return HIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.HIREDATE
     *
     * @param HIREDATE the value for DBUSER.EMP.HIREDATE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setHIREDATE(Date HIREDATE) {
        this.HIREDATE = HIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.SAL
     *
     * @return the value of DBUSER.EMP.SAL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public BigDecimal getSAL() {
        return SAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.SAL
     *
     * @param SAL the value for DBUSER.EMP.SAL
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setSAL(BigDecimal SAL) {
        this.SAL = SAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.COMM
     *
     * @return the value of DBUSER.EMP.COMM
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public BigDecimal getCOMM() {
        return COMM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.COMM
     *
     * @param COMM the value for DBUSER.EMP.COMM
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCOMM(BigDecimal COMM) {
        this.COMM = COMM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.EMP.DEPTNO
     *
     * @return the value of DBUSER.EMP.DEPTNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getDEPTNO() {
        return DEPTNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.EMP.DEPTNO
     *
     * @param DEPTNO the value for DBUSER.EMP.DEPTNO
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setDEPTNO(Short DEPTNO) {
        this.DEPTNO = DEPTNO;
    }
}