package demo.model.dao;

import demo.model.dao.OrdersItems;
import demo.model.dao.OrdersItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    long countByExample(OrdersItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByExample(OrdersItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByPrimaryKey(Short ORDER_ITEM_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insert(OrdersItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insertSelective(OrdersItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    List<OrdersItems> selectByExample(OrdersItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    OrdersItems selectByPrimaryKey(Short ORDER_ITEM_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExampleSelective(@Param("record") OrdersItems record, @Param("example") OrdersItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExample(@Param("record") OrdersItems record, @Param("example") OrdersItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKeySelective(OrdersItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_ORDER_ITEMS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKey(OrdersItems record);
}