package demo.model.dao;

import java.math.BigDecimal;

public class OrdersItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ITEM_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short ORDER_ITEM_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short ORDER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short PRODUCT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_ORDER_ITEMS.UNIT_PRICE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private BigDecimal UNIT_PRICE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_ORDER_ITEMS.QUANTITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Integer QUANTITY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ITEM_ID
     *
     * @return the value of DBUSER.DEMO_ORDER_ITEMS.ORDER_ITEM_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getORDER_ITEM_ID() {
        return ORDER_ITEM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ITEM_ID
     *
     * @param ORDER_ITEM_ID the value for DBUSER.DEMO_ORDER_ITEMS.ORDER_ITEM_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setORDER_ITEM_ID(Short ORDER_ITEM_ID) {
        this.ORDER_ITEM_ID = ORDER_ITEM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ID
     *
     * @return the value of DBUSER.DEMO_ORDER_ITEMS.ORDER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getORDER_ID() {
        return ORDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_ORDER_ITEMS.ORDER_ID
     *
     * @param ORDER_ID the value for DBUSER.DEMO_ORDER_ITEMS.ORDER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setORDER_ID(Short ORDER_ID) {
        this.ORDER_ID = ORDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_ORDER_ITEMS.PRODUCT_ID
     *
     * @return the value of DBUSER.DEMO_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getPRODUCT_ID() {
        return PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_ORDER_ITEMS.PRODUCT_ID
     *
     * @param PRODUCT_ID the value for DBUSER.DEMO_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setPRODUCT_ID(Short PRODUCT_ID) {
        this.PRODUCT_ID = PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_ORDER_ITEMS.UNIT_PRICE
     *
     * @return the value of DBUSER.DEMO_ORDER_ITEMS.UNIT_PRICE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public BigDecimal getUNIT_PRICE() {
        return UNIT_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_ORDER_ITEMS.UNIT_PRICE
     *
     * @param UNIT_PRICE the value for DBUSER.DEMO_ORDER_ITEMS.UNIT_PRICE
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setUNIT_PRICE(BigDecimal UNIT_PRICE) {
        this.UNIT_PRICE = UNIT_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_ORDER_ITEMS.QUANTITY
     *
     * @return the value of DBUSER.DEMO_ORDER_ITEMS.QUANTITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Integer getQUANTITY() {
        return QUANTITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_ORDER_ITEMS.QUANTITY
     *
     * @param QUANTITY the value for DBUSER.DEMO_ORDER_ITEMS.QUANTITY
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setQUANTITY(Integer QUANTITY) {
        this.QUANTITY = QUANTITY;
    }
}