package demo.model.dao;

import demo.model.dao.ProductInfo;
import demo.model.dao.ProductInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    long countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_STATES
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);
}