package demo.model.dao;

public class ProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_STATES.ST
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String ST;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_STATES.STATE_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String STATE_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_STATES.ST
     *
     * @return the value of DBUSER.DEMO_STATES.ST
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getST() {
        return ST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_STATES.ST
     *
     * @param ST the value for DBUSER.DEMO_STATES.ST
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setST(String ST) {
        this.ST = ST == null ? null : ST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_STATES.STATE_NAME
     *
     * @return the value of DBUSER.DEMO_STATES.STATE_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getSTATE_NAME() {
        return STATE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_STATES.STATE_NAME
     *
     * @param STATE_NAME the value for DBUSER.DEMO_STATES.STATE_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setSTATE_NAME(String STATE_NAME) {
        this.STATE_NAME = STATE_NAME == null ? null : STATE_NAME.trim();
    }
}