package demo.model.dao;

import demo.model.dao.Users;
import demo.model.dao.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int deleteByPrimaryKey(Short USER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    Users selectByPrimaryKey(Short USER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBUSER.DEMO_USERS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    int updateByPrimaryKey(Users record);
}