package demo.model.dao;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.USER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short USER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.USER_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String USER_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.PASSWORD
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String PASSWORD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.CREATED_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Date CREATED_ON;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.QUOTA
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Short QUOTA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.PRODUCTS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String PRODUCTS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.EXPIRES_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private Date EXPIRES_ON;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DBUSER.DEMO_USERS.ADMIN_USER
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    private String ADMIN_USER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.USER_ID
     *
     * @return the value of DBUSER.DEMO_USERS.USER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.USER_ID
     *
     * @param USER_ID the value for DBUSER.DEMO_USERS.USER_ID
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setUSER_ID(Short USER_ID) {
        this.USER_ID = USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.USER_NAME
     *
     * @return the value of DBUSER.DEMO_USERS.USER_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getUSER_NAME() {
        return USER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.USER_NAME
     *
     * @param USER_NAME the value for DBUSER.DEMO_USERS.USER_NAME
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME == null ? null : USER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.PASSWORD
     *
     * @return the value of DBUSER.DEMO_USERS.PASSWORD
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.PASSWORD
     *
     * @param PASSWORD the value for DBUSER.DEMO_USERS.PASSWORD
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.CREATED_ON
     *
     * @return the value of DBUSER.DEMO_USERS.CREATED_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Date getCREATED_ON() {
        return CREATED_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.CREATED_ON
     *
     * @param CREATED_ON the value for DBUSER.DEMO_USERS.CREATED_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setCREATED_ON(Date CREATED_ON) {
        this.CREATED_ON = CREATED_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.QUOTA
     *
     * @return the value of DBUSER.DEMO_USERS.QUOTA
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Short getQUOTA() {
        return QUOTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.QUOTA
     *
     * @param QUOTA the value for DBUSER.DEMO_USERS.QUOTA
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setQUOTA(Short QUOTA) {
        this.QUOTA = QUOTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.PRODUCTS
     *
     * @return the value of DBUSER.DEMO_USERS.PRODUCTS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getPRODUCTS() {
        return PRODUCTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.PRODUCTS
     *
     * @param PRODUCTS the value for DBUSER.DEMO_USERS.PRODUCTS
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setPRODUCTS(String PRODUCTS) {
        this.PRODUCTS = PRODUCTS == null ? null : PRODUCTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.EXPIRES_ON
     *
     * @return the value of DBUSER.DEMO_USERS.EXPIRES_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public Date getEXPIRES_ON() {
        return EXPIRES_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.EXPIRES_ON
     *
     * @param EXPIRES_ON the value for DBUSER.DEMO_USERS.EXPIRES_ON
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setEXPIRES_ON(Date EXPIRES_ON) {
        this.EXPIRES_ON = EXPIRES_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DBUSER.DEMO_USERS.ADMIN_USER
     *
     * @return the value of DBUSER.DEMO_USERS.ADMIN_USER
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public String getADMIN_USER() {
        return ADMIN_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DBUSER.DEMO_USERS.ADMIN_USER
     *
     * @param ADMIN_USER the value for DBUSER.DEMO_USERS.ADMIN_USER
     *
     * @mbg.generated Mon Nov 06 13:15:56 GMT 2017
     */
    public void setADMIN_USER(String ADMIN_USER) {
        this.ADMIN_USER = ADMIN_USER == null ? null : ADMIN_USER.trim();
    }
}